#pragma once

#include "NormDeviationMap.h"
#include "NormETDRS.h"
#include "NormGCC.h"
#include "NormArchive.h"
#include "NormClockNFL.h"
#include "NormClockRPE.h"
#include "NormQuadNFL.h"
#include "NormQuadRPE.h"
#include "NormTSNIT.h"
#include "NormDiscNFL.h"
#include "NormDiscRPE.h"
#include "NormDiscInfo.h"
#include "NormMacularIPL.h"
#include "NormMacularRPE.h"
#include "NormBisectGCC.h"
#include "NormRNFLAverage.h"
#include "NormRNFLSymmetry.h"

#include "DiscRnflTsnitGraph.h"