#pragma once

namespace wso_domain
{
	// Constant Definitions
	/////////////////////////////////////////////////////////////////////////////////////////////
	constexpr float IR_CORNEA_AGAIN_INIT = 1.0f;
	constexpr float IR_CORNEA_DGAIN_INIT = 1.0f;

	constexpr int N_WORKING_DOTS = 2;
	constexpr int IR_WDOT_INTENSITY_INIT = 20;
	constexpr int IR_WDOT_INTENSITY_MIN = 0;
	constexpr int IR_WDOT_INTENSITY_MAX = 100;


	// Fundus color camera
	//////////////////////////////////////////////////////////////////////////////////////////////
	constexpr int FUNDUS_FRAME_WIDTH = 3840;
	constexpr int FUNDUS_FRAME_HEIGHT = 3000;
	constexpr int FUNDUS_FRAME_SIZE = (FUNDUS_FRAME_WIDTH * FUNDUS_FRAME_HEIGHT);
	constexpr int FUNDUS_FRAME_DEPTH = 3;

	constexpr int FUNDUS_FRAME_BUFFER_SIZE = (FUNDUS_FRAME_SIZE * FUNDUS_FRAME_DEPTH);

	constexpr int FUNDUS_IMAGE_MASK_SIZE = 2840;
	constexpr int FUNDUS_IMAGE_MASK_RADIUS = (FUNDUS_IMAGE_MASK_SIZE / 2);
	constexpr int FUNDUS_IMAGE_WIDTH = FUNDUS_IMAGE_MASK_SIZE;
	constexpr int FUNDUS_IMAGE_HEIGHT = FUNDUS_IMAGE_MASK_SIZE;
	constexpr int FUNDUS_IMAGE_SIZE = (FUNDUS_IMAGE_WIDTH * FUNDUS_IMAGE_HEIGHT);
	constexpr int FUNDUS_IMAGE_DEPTH = 3;

	constexpr int FUNDUS_IMAGE_BUFFER_SIZE = (FUNDUS_IMAGE_SIZE * FUNDUS_IMAGE_DEPTH);

	constexpr float FUNDUS_AWB_INIT_PARAM1 = 1.0f;
	constexpr float FUNDUS_AWB_INIT_PARAM2 = 1.0f;
	constexpr int FUNDUS_AWB_PARAMS_SIZE = 2;

	constexpr int FUNDUS_RADIAL_CORRECT_INIT_PARAM1_X = 0;
	constexpr int FUNDUS_RADIAL_CORRECT_INIT_PARAM1_Y = 0;
	constexpr int FUNDUS_RADIAL_CORRECT_INIT_PARAM2_X = 256;
	constexpr int FUNDUS_RADIAL_CORRECT_INIT_PARAM2_Y = 768;
	constexpr int FUNDUS_RADIAL_CORRECT_INIT_PARAM3_X = 512;
	constexpr int FUNDUS_RADIAL_CORRECT_INIT_PARAM3_Y = 1024;
	constexpr int FUNDUS_RADIAL_CORRECT_INIT_PARAM4_X = 4095;
	constexpr int FUNDUS_RADIAL_CORRECT_INIT_PARAM4_Y = 4095;
	constexpr int FUNDUS_RADIAL_CORRECT_PARAMS_SIZE = 4;

	constexpr int FUNDUS_ROI_INIT_CENTER_X = 1880; //  FUNDUS_FRAME_WIDTH / 2;
	constexpr int FUNDUS_ROI_INIT_CENTER_Y = 1465; // FUNDUS_FRAME_HEIGHT / 2;
	constexpr int FUNDUS_ROI_INIT_RADIUS = 1380; // FUNDUS_IMAGE_MASK_RADIUS;

	constexpr int FUNDUS_REMOVE_REFLECTION_INIT_LIGHT = 135;
	constexpr int FUNDUS_REMOVE_REFLECTION_INIT_SHADOW = 240;
	constexpr int FUNDUS_REMOVE_REFLECTION_INIT_OUTER = 290;

	//FILR Fundus Camera Parameter
	/////////////////////////////////////////////////////////////////////////////////	
	constexpr int FUNDUS_FILR_FRAME_WIDTH = 4668;
	constexpr int FUNDUS_FILR_FRAME_HEIGHT = 3648;
	constexpr int FUNDUS_FILR_FRAME_SIZE = (FUNDUS_FILR_FRAME_WIDTH * FUNDUS_FILR_FRAME_HEIGHT);
	constexpr int FUNDUS_FILR_FRAME_DEPTH = 3;

	constexpr int FUNDUS_FILR_FRAME_BUFFER_SIZE = (FUNDUS_FILR_FRAME_SIZE * FUNDUS_FILR_FRAME_DEPTH);

	constexpr int FUNDUS_FILR_IMAGE_MASK_SIZE = 3200;
	constexpr int FUNDUS_FILR_IMAGE_MASK_RADIUS = (FUNDUS_FILR_IMAGE_MASK_SIZE / 2);
	constexpr int FUNDUS_FILR_IMAGE_WIDTH = FUNDUS_FILR_IMAGE_MASK_SIZE;
	constexpr int FUNDUS_FILR_IMAGE_HEIGHT = FUNDUS_FILR_IMAGE_MASK_SIZE;
	constexpr int FUNDUS_FILR_IMAGE_SIZE = (FUNDUS_FILR_IMAGE_WIDTH * FUNDUS_FILR_IMAGE_HEIGHT);
	constexpr int FUNDUS_FILR_IMAGE_DEPTH = 3;

	constexpr int FUNDUS_FILR_IMAGE_BUFFER_SIZE = (FUNDUS_FILR_IMAGE_SIZE * FUNDUS_FILR_IMAGE_DEPTH);

	constexpr float FUNDUS_FILR_AWB_INIT_PARAM1 = 1.0f;
	constexpr float FUNDUS_FILR_AWB_INIT_PARAM2 = 1.0f;
	constexpr int FUNDUS_FILR_AWB_PARAMS_SIZE = 2;

	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM1_X = 0;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM1_Y = 0;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM2_X = 128;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM2_Y = 512;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM3_X = 256;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM3_Y = 768;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM4_X = 512;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM4_Y = 4096;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM5_X = 1024;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM5_Y = 8192;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM6_X = 4096;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM6_Y = 16384;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM7_X = 32767;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_INIT_PARAM7_Y = 32767;
	constexpr int FUNDUS_FILR_RADIAL_CORRECT_PARAMS_SIZE = 7;

	constexpr int FUNDUS_FILR_ROI_INIT_CENTER_X = 2334;
	constexpr int FUNDUS_FILR_ROI_INIT_CENTER_Y = 1824;
	constexpr int FUNDUS_FILR_ROI_INIT_RADIUS = 1600;

	constexpr int FUNDUS_FILR_REMOVE_REFLECTION_INIT_LIGHT = 135;
	constexpr int FUNDUS_FILR_REMOVE_REFLECTION_INIT_SHADOW = 300;
	constexpr int FUNDUS_FILR_REMOVE_REFLECTION_INIT_OUTER = 330;
	////////////////////////////////////////////////////////////////////////////

	constexpr float FUNDUS_ZERO_LENS_DIOPT = 0.0f;
	constexpr float FUNDUS_ZERO_LENS_DIOPT_MAX = +13.0f;
	constexpr float FUNDUS_ZERO_LENS_DIOPT_MIN = -13.0f;
	constexpr float FUNDUS_MINUS_LENS_DIOPT = -20.0f;
	constexpr float FUNDUS_MINUS_LENS_DIOPT_MAX = (FUNDUS_MINUS_LENS_DIOPT + FUNDUS_ZERO_LENS_DIOPT_MAX);
	constexpr float FUNDUS_MINUS_LENS_DIOPT_MIN = (FUNDUS_MINUS_LENS_DIOPT + FUNDUS_ZERO_LENS_DIOPT_MIN);
	constexpr float FUNDUS_PLUS_LENS_DIOPT = +20.0f;
	constexpr float FUNDUS_PLUS_LENS_DIOPT_MAX = (FUNDUS_PLUS_LENS_DIOPT + FUNDUS_ZERO_LENS_DIOPT_MAX);
	constexpr float FUNDUS_PLUS_LENS_DIOPT_MIN = (FUNDUS_PLUS_LENS_DIOPT + FUNDUS_ZERO_LENS_DIOPT_MIN);

	constexpr int AUTO_FLASH_LEVEL_PRESET_SIZE = 3;
	constexpr int FlashPresetFocusInts[AUTO_FLASH_LEVEL_PRESET_SIZE] = { 250, 225, 200 };
	constexpr int FlashPresetSizeBases[AUTO_FLASH_LEVEL_PRESET_SIZE] = { 13, 11, 8 };
	constexpr int FlashPresetSizeHighs[AUTO_FLASH_LEVEL_PRESET_SIZE] = { 26, 22, 16 };
	constexpr int FlashPresetDefLevels[AUTO_FLASH_LEVEL_PRESET_SIZE] = { 60, 40, 30 };

	constexpr int FLASH_PRESET_SIZE_MIN = 0;
	constexpr int FLASH_PRESET_SIZE_MAX = 99;
	constexpr int FLASH_PRESET_INT_MIN = 0;
	constexpr int FLASH_PRESET_INT_MAX = 255;
}